### ISSUE TITLE
Update gender selection in user profile

### ISSUE THREAD

**Issue by Daenyth** [woogerboy21/servatriceadminwebui#13]
The gender selection should have the following options (with db values)

```
Unspecified -> ""
Masculine -> "m"
Feminine -> "f"
Neutral -> "n"
```

If it's possible to show the icons from cockatrice next to the words it would be nice, but not necessary

**Comment by Daenyth** [comment]
cc @ZeldaZach

**Comment by ZeldaZach** [comment]
Gotcah, will look into this

**Comment by Daenyth** [comment]
Thanks
